#include "../defines.h"

volatile uint8_t *FLAGS_READER = (uint8_t *)(READER);
volatile UINT *ADDR_READER_ADDR_FROM = (volatile UINT *)(READER + 1);
volatile UINT *ADDR_READER_STREAM_TO = (volatile UINT *)(READER + 9);

volatile uint8_t *FLAGS_FILTER = (uint8_t *)(FILTER);
volatile UINT *ADDR_FILTER_STREAM_FROM = (volatile UINT *)(FILTER + 1);
volatile UINT *ADDR_FILTER_STREAM_TO = (volatile UINT *)(FILTER + 9);

volatile uint8_t *FLAGS_MAP = (uint8_t *)(MAP);
volatile UINT *ADDR_MAP_STREAM_FROM = (volatile UINT *)(MAP + 1);
volatile UINT *ADDR_MAP_STREAM_TO = (volatile UINT *)(MAP + 9);

volatile uint8_t *FLAGS_BRANCH = (uint8_t *)(BRANCH);
volatile UINT *ADDR_BRANCH_STREAM_FROM = (volatile UINT *)(BRANCH + 1);
volatile UINT *ADDR_BRANCH_STREAM_TO_0 = (volatile UINT *)(BRANCH + 9);
volatile UINT *ADDR_BRANCH_STREAM_TO_1 = (volatile UINT *)(BRANCH + 17);
volatile UINT *ADDR_BRANCH_STREAM_TO_2 = (volatile UINT *)(BRANCH + 25);

volatile uint8_t *FLAGS_MERGE = (uint8_t *)(MERGE);
volatile UINT *ADDR_MERGE_STREAM_FROM_0 = (volatile UINT *)(MERGE + 1);
volatile UINT *ADDR_MERGE_STREAM_FROM_1 = (volatile UINT *)(MERGE + 9);
volatile UINT *ADDR_MERGE_STREAM_FROM_2 = (volatile UINT *)(MERGE + 17);
volatile UINT *ADDR_MERGE_STREAM_TO = (volatile UINT *)(MERGE + 25);

volatile uint8_t *FLAGS_TO_TABLE = (uint8_t *)(TO_TABLE);
volatile UINT *ADDR_TO_TABLE_STREAM_FROM = (volatile UINT *)(TO_TABLE + 1);
volatile UINT *ADDR_TO_TABLE_TABLE_TO = (volatile UINT *)(TO_TABLE + 9);

void top(ADDR addr_clicks, ADDR addr_table) {

  *ADDR_READER_ADDR_FROM = addr_clicks;
  *ADDR_READER_STREAM_TO = STREAM_CLICK_EVENTS;
  *ADDR_FILTER_STREAM_FROM = STREAM_CLICK_EVENTS;
  *ADDR_FILTER_STREAM_TO = STREAM_FILTERED_CLICK_EVENTS;
  *ADDR_MAP_STREAM_FROM = STREAM_FILTERED_CLICK_EVENTS;
  *ADDR_MAP_STREAM_TO = STREAM_MAPPED_CLICK_EVENTS;
  *ADDR_BRANCH_STREAM_FROM = STREAM_MAPPED_CLICK_EVENTS;
  *ADDR_BRANCH_STREAM_TO_0 = STREAM_LOW_CLICK_EVENTS;
  *ADDR_BRANCH_STREAM_TO_1 = STREAM_MID_CLICK_EVENTS;
  *ADDR_BRANCH_STREAM_TO_2 = STREAM_DEFAULT_CLICK_EVENTS;
  *ADDR_MERGE_STREAM_FROM_0 = STREAM_LOW_CLICK_EVENTS;
  *ADDR_MERGE_STREAM_FROM_1 = STREAM_MID_CLICK_EVENTS;
  *ADDR_MERGE_STREAM_FROM_2 = STREAM_DEFAULT_CLICK_EVENTS;
  *ADDR_MERGE_STREAM_TO = STREAM_MERGED_CLICK_EVENTS;
  *ADDR_TO_TABLE_STREAM_FROM = STREAM_MERGED_CLICK_EVENTS;
  *ADDR_TO_TABLE_TABLE_TO = addr_table;

  *FLAGS_READER = DEV_INIT;
  *FLAGS_FILTER = DEV_INIT;
  *FLAGS_MAP = DEV_INIT;
  *FLAGS_BRANCH = DEV_INIT;
  *FLAGS_MERGE = DEV_INIT;
  *FLAGS_TO_TABLE = DEV_INIT;

  while ((*FLAGS_READER & DEV_INTR) != DEV_INTR)
    ;
  while ((*FLAGS_FILTER & DEV_INTR) != DEV_INTR)
    ;
  while ((*FLAGS_MAP & DEV_INTR) != DEV_INTR)
    ;
  while ((*FLAGS_BRANCH & DEV_INTR) != DEV_INTR)
    ;
  while ((*FLAGS_MERGE & DEV_INTR) != DEV_INTR)
    ;
  while ((*FLAGS_TO_TABLE & DEV_INTR) != DEV_INTR)
    ;

  return;
}
